<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>SharedMemory.IpcHelper</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedMemory\SharedMemory.csproj" />
  </ItemGroup>

</Project>
